# Generated by Django 4.2.4 on 2023-10-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminview', '0004_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeredproduct',
            name='percentage_discount',
            field=models.DecimalField(decimal_places=2, default=0.15, max_digits=5),
        ),
    ]
